import Vue from "vue";
import Page from "~/components/Page";
import Header from "~/components/Header";
import Home from "~/components/Home";
import TextImage from "~/components/TextImage";
import Partners from "~/components/Partners";
import NewsletterCTA from "~/components/NewsletterCTA";
import Paragraph from "~/components/Paragraph";
import Feature from "~/components/Feature";
import HalfText from "~/components/HalfText";
import TwoImageGrid from "~/components/TwoImageGrid";
import ThreeImageGrid from "~/components/ThreeImageGrid";
import SingleImage from "~/components/SingleImage";
import OnTap from "~/components/OnTap";
import FullImage from "~/components/FullImage";
import TextWithButton from "~/components/TextWithButton";
import LocationsMap from "~/components/LocationsMap";
import ContactForm from "~/components/ContactForm";
import ContactAddressHours from "~/components/ContactAddressHours";
import BeerToGo from "~/components/BeerToGo";
import CenteredText from "~/components/CenteredText";
import EventsForm from "~/components/EventsForm";
import AwardsBlock from "~/components/AwardsBlock";
import BeersCTABlock from "~/components/BeersCTABlock";
import HomeGrid from "~/components/HomeGrid";
import Testimonial from "~/components/Testimonial";

Vue.component("page", Page);
Vue.component("heading", Header);
Vue.component("home", Home);
Vue.component("TextImage", TextImage);
Vue.component("Partners", Partners);
Vue.component("NewsletterCTA", NewsletterCTA);
Vue.component("Paragraph", Paragraph);
Vue.component("Feature", Feature);
Vue.component("HalfText", HalfText);
Vue.component("two_image_grid", TwoImageGrid);
Vue.component("three_image_grid", ThreeImageGrid);
Vue.component("SingleImage", SingleImage);
Vue.component("OnTap", OnTap);
Vue.component("full_image", FullImage);
Vue.component("text_with_button", TextWithButton);
Vue.component("locations_map", LocationsMap);
Vue.component("contact_form", ContactForm);
Vue.component("contact_address_hours", ContactAddressHours);
Vue.component("beer_to_go", BeerToGo);
Vue.component("centered_text", CenteredText);
Vue.component("events_form", EventsForm);
Vue.component("awards_block", AwardsBlock);
Vue.component("beers_cta_block", BeersCTABlock);
Vue.component("home_grid", HomeGrid);
Vue.component("testimonial", Testimonial);
